ARG BASE_IMAGE
FROM ${BASE_IMAGE} as build
ARG NODEJS_VERSION
RUN ln -fs /usr/share/zoneinfo/Europe/Istanbul /etc/localtime
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tzdata
RUN apt-get install -y git npm
RUN npm install -g n
RUN n ${NODEJS_VERSION}
WORKDIR /home/robolaunch
USER root

