ARG BASE_IMAGE
FROM ${BASE_IMAGE} as build
ARG JUPYTER_VERSION
USER root
RUN apt-get update
RUN apt-get install -y git build-essential libopencv-dev python3-opencv vim mlocate python3-pip python3-venv python3-dev python-is-python3
USER robolaunch
ENV PATH=$PATH:/home/robolaunch/.local/bin
RUN echo 'export PATH=$PATH:/home/robolaunch/.local/bin' >> ~/.bashrc
ENV PYTHONPATH "/home/robolaunch/.local/lib/python3.8/:${PYTHONPATH}"
ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1
RUN python -m pip install notebook==${JUPYTER_VERSION}
WORKDIR /home/robolaunch
USER root


