ARG BASE_IMAGE
FROM ${BASE_IMAGE} as build
ARG CSHARP_VERSION
RUN wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
RUN dpkg -i packages-microsoft-prod.deb
RUN rm packages-microsoft-prod.deb
RUN apt-get update && apt-get install -y dotnet-sdk-${CSHARP_VERSION}
WORKDIR /home/robolaunch
USER root

