FROM quay.io/robolaunchio/devspace-aiml:custom-auto-01-09202023-focal-xfce-0.1.6

RUN apt-get update && apt-get install --only-upgrade -y \
    libksba8 \
    openssl \
    ncurses-bin \
    libtinfo5 \
    libperl5.30 \
    libncursesw5 \
    xxd \
    libctf0 \
    libbinutils \
    logsave \
    libxml2 \
    libcap2 \
    libcap2-bin \
    libext2fs2 \
    binutils-common \
    binutils-x86-64-linux-gnu \
    openmpi-common \
    libslurm34 \
    libpmi2-0 \
    libopenmpi3 \
    openmpi-bin \
    libpmix2

# RUN pip3 install -U \
#     setuptools \
#     wheel

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]