FROM quay.io/openebs/linux-utils:3.4.0

RUN apk update && apk upgrade \
    e2fsprogs-libs \
    e2fsprogs-extra \
    python3 \
    libssl1.1 \
    expat \
    libcrypto1.1 \
    libcom_err \
    e2fsprogs