ARG BASE_IMAGE
FROM ${BASE_IMAGE} as build
RUN add-apt-repository --yes ppa:kicad/kicad-7.0-releases
RUN apt-get update && apt-get install -y --install-recommends kicad
WORKDIR /home/robolaunch
USER root