ARG BASE_IMAGE
FROM ${BASE_IMAGE} as build
RUN apt-get update && apt-get install -y pyqt5-dev-tools
USER robolaunch
RUN wget -P /home/robolaunch https://qcad.org/archives/qcad/qcad-3.28.1-trial-linux-qt5.14-x86_64.run
RUN bash /home/robolaunch/qcad-3.28.1-trial-linux-qt5.14-x86_64.run
RUN rm /home/robolaunch/qcad-3.28.1-trial-linux-qt5.14-x86_64.run
USER root
WORKDIR /home/robolaunch