ARG BASE_IMAGE
FROM ${BASE_IMAGE} as build
ARG QCAD_VERSION
RUN apt-get update && apt-get install -y pyqt5-dev-tools
USER robolaunch
RUN wget -P /home/robolaunch https://qcad.org/archives/qcad/qcad-${QCAD_VERSION}.run
RUN bash /home/robolaunch/qcad-${QCAD_VERSION}.run
RUN rm /home/robolaunch/qcad-${QCAD_VERSION}.run
USER root
WORKDIR /home/robolaunch