ARG BASE_IMAGE=robolaunchio/vdi:focal-agnostic-xfce-withuser
FROM ${BASE_IMAGE} as build
RUN apt-get install -y freecad libnglib-dev python3-pyqt5
RUN ln -s /usr/lib/x86_64-linux-gnu/netgen/*.so /usr/lib/
WORKDIR /home/robolaunch
USER root