FROM quay.io/robolaunchio/platform-initial:gpu-feature-discovery-v0.8.1

RUN dnf upgrade -y \
    python3-cloud-what \
    dnf-plugin-subscription-manager \
    subscription-manager-rhsm-certificates \
    python3-syspurpose \
    python3-subscription-manager-rhsm \
    subscription-manager

ENTRYPOINT ["/usr/bin/gpu-feature-discovery"]